#!/usr/bin/env python3
"""Fold lang/*.json into WorkLogApp.v2.dc.html as Component.STR.

lang/base.json holds ko + en for every key and is the reference wording.
lang/<code>.json holds one language's values, keyed the same way.
Adding a language is adding a file — no code changes.

    python3 tools/sync_lang.py            check + write
    python3 tools/sync_lang.py --report   coverage only, writes nothing
"""
import io
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'WorkLogApp.v2.dc.html')
LANG = os.path.join(ROOT, 'lang')

BEGIN = '  // <<<LANG-TABLE — generated by tools/sync_lang.py, edit lang/*.json instead'
END = '  // LANG-TABLE>>>'

# date lists are per-language data, not sentences; they live in base.json too
EXTRA_LANGS = ['vi', 'zh', 'th', 'id', 'ne', 'km']


def main():
    base = json.load(io.open(os.path.join(LANG, 'base.json'), encoding='utf-8'))
    table = {}
    for k, v in base.items():
        table[k] = {'ko': v['ko'], 'en': v['en']}

    report = []
    for code in EXTRA_LANGS:
        p = os.path.join(LANG, code + '.json')
        if not os.path.exists(p):
            report.append((code, 0, len(base), 'no file'))
            continue
        d = json.load(io.open(p, encoding='utf-8'))
        unknown = [k for k in d if k not in base]
        have = 0
        for k, v in d.items():
            if k not in base:
                continue
            if isinstance(v, str) and v.strip():
                table[k][code] = v
                have += 1
        report.append((code, have, len(base), ('%d unknown key(s)' % len(unknown)) if unknown else ''))

    print('%-6s %-16s %s' % ('lang', 'translated', 'note'))
    for code, have, total, note in report:
        pct = (100.0 * have / total) if total else 0
        print('%-6s %4d / %-4d %5.1f%%   %s' % (code, have, total, pct, note))

    if '--report' in sys.argv:
        return

    blob = json.dumps(table, ensure_ascii=False, sort_keys=True, separators=(',', ':'))
    src = io.open(SRC, encoding='utf-8').read()
    line = '  static STR = ' + blob + ';'
    block = BEGIN + '\n' + line + '\n' + END

    if BEGIN in src:
        a = src.index(BEGIN)
        b = src.index(END) + len(END)
        src = src[:a] + block + src[b:]
    else:
        anchor = '  static LANGS = ['
        if anchor not in src:
            sys.exit('could not find the anchor to insert the table before')
        i = src.index(anchor)
        src = src[:i] + block + '\n' + src[i:]

    io.open(SRC, 'w', encoding='utf-8').write(src)
    print('\nwrote Component.STR — %d keys, %d languages, %d KB'
          % (len(table), 2 + len([r for r in report if r[1]]), len(blob) // 1024))


if __name__ == '__main__':
    main()
